/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   get_unique_hd_filename.c                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mniemaz <mniemaz@student.42lyon.fr>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/05/29 19:07:46 by mniemaz           #+#    #+#             */
/*   Updated: 2025/05/29 19:10:02 by mniemaz          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

static char	*get_incremented_hd_name(size_t hd_i)
{
	char	*str_hd_i;
	char	*hd_name;

	str_hd_i = ft_itoa(hd_i);
	if (!str_hd_i)
		return (NULL);
	hd_name = ft_strjoin(HD_FILENAME, str_hd_i);
	free(str_hd_i);
	if (!hd_name)
		return (NULL);
	return (hd_name);
}

/**
 * @brief Generates a unique heredoc filename.
 * It is generated by appending an incrementing number to the base
 */
char	*get_unique_hd_filename(void)
{
	char	*hd_name;
	size_t	hd_i;

	hd_i = 0;
	hd_name = get_incremented_hd_name(hd_i);
	if (!hd_name)
		return (NULL);
	while (access(hd_name, F_OK) == 0)
	{
		free(hd_name);
		hd_name = get_incremented_hd_name(hd_i);
		if (!hd_name)
			return (NULL);
		hd_i++;
	}
	return (hd_name);
}
