/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   handle_heredoc.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mniemaz <mniemaz@student.42lyon.fr>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/05/27 15:21:53 by mniemaz           #+#    #+#             */
/*   Updated: 2025/05/27 15:46:11 by mniemaz          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

char	*get_incremented_hd_name(size_t hd_i)
{
	char	*str_hd_i;
	char	*hd_name;

	str_hd_i = ft_itoa(hd_i);
	if (!str_hd_i)
	{
		printf("hd todo");
		return (NULL);
	}
	hd_name = ft_strjoin(HD_FILENAME, str_hd_i);
	if (!hd_name)
	{
		printf("hd todo");
		return (NULL);
	}
	free(str_hd_i);
	return (hd_name);
}
/**
 * @brief Generates a unique heredoc filename.
 * It is generated by appending an incrementing number to the base
 */
char	*get_hd_name(void)
{
	char	*hd_name;
	size_t	hd_i;

	hd_i = 0;
	hd_name = get_incremented_hd_name(hd_i);
	while (access(hd_name, F_OK) == 0)
	{
		free(hd_name);
		hd_name = get_incremented_hd_name(hd_i);
		hd_i++;
	}
	return (hd_name);
}

void	write_in_file(int hd_fd, char *eof, t_context *ctx)
{
	char		*line;

	while (g_signal == 0)
	{
		write(STDOUT_FILENO, "> ", 2);
		line = get_next_line(STDIN_FILENO);
		if (!line && g_signal == 0)
		{
			write(STDERR_FILENO, "\n", 1);
				ft_fprintf(STDERR_FILENO, "warning: here-document \
delimited by end-of-file (wanted `%s')\n", eof);
			break ;
		}
		line = interpretation(line, ctx);
		if (!line || !ft_strncmp(rm_last_char(line), eof, ft_strlen(eof) + 1))
			break ;
		write(hd_fd, line, ft_strlen(line));
		write(hd_fd, "\n", 1);
		free(line);
	}
	close(hd_fd);
	free(eof);
	free(line);
}

int	wait_hd_child(t_context *ctx)
{
	int	status;

	status = 0;
	waitpid(ctx->hd_pid, &status, 0);
	if (WIFEXITED(status))
	{
		if (WEXITSTATUS(status))
		{
			if (WEXITSTATUS(status) > 128)
			{
				write(STDERR_FILENO, "\n", 1);
				g_signal = WEXITSTATUS(status) - 128;
			}
			ctx->exit_code = WEXITSTATUS(status);
			return (EXIT_FAILURE);
		}
	}
	return (EXIT_SUCCESS);
}

int	handle_heredoc(t_context *ctx, char *str, size_t *i, t_redirect **redir_addr)
{
	int		hd_fd;
	char	*eof;

    t_redirect *redir;

    redir = *redir_addr;

	redir->filename = get_hd_name();
	hd_fd = open(redir->filename, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (hd_fd == -1)
		return (EXIT_FAILURE);
	eof = malloc(redirlen(str) + 1);
	if (!eof)
	{
		close(hd_fd);
		return (EXIT_FAILURE);
	}
	*i += extract_redirection_filename(str + *i, eof);
	// todo secure signal
	signal(SIGINT, SIG_IGN);
	secure_fork(&ctx->hd_pid, ctx);
	if (!ctx->hd_pid)
	{
		install_sigint_handler(hd_sigint_handler);
		write_in_file(hd_fd, eof, ctx);
		// free(redir->filename);
		return (EXIT_FAILURE);
	}
	close(hd_fd);
	free(eof);
	if (wait_hd_child(ctx) == EXIT_FAILURE)
	{
		// unlink(redir->filename);
		// free(redir->filename);
		return (EXIT_FAILURE);
	}
	return (EXIT_SUCCESS);
}
