/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   handle_heredoc.c                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mniemaz <mniemaz@student.42lyon.fr>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/05/27 15:21:53 by mniemaz           #+#    #+#             */
/*   Updated: 2025/05/29 11:02:54 by mniemaz          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

static char	*get_incremented_hd_name(size_t hd_i)
{
	char	*str_hd_i;
	char	*hd_name;

	str_hd_i = ft_itoa(hd_i);
	if (!str_hd_i)
		return (NULL);
	hd_name = ft_strjoin(HD_FILENAME, str_hd_i);
	free(str_hd_i);
	if (!hd_name)
		return (NULL);
	return (hd_name);
}
/**
 * @brief Generates a unique heredoc filename.
 * It is generated by appending an incrementing number to the base
 */
static char	*get_hd_name(void)
{
	char	*hd_name;
	size_t	hd_i;

	hd_i = 0;
	hd_name = get_incremented_hd_name(hd_i);
	if (!hd_name)
		return (NULL);
	while (access(hd_name, F_OK) == 0)
	{
		free(hd_name);
		hd_name = get_incremented_hd_name(hd_i);
		if (!hd_name)
			return (NULL);
		hd_i++;
	}
	return (hd_name);
}

static void	write_in_file(int hd_fd, char *eof, t_context *ctx,
		t_redir_type redir_type)
{
	char	*line;

	while (g_signal == 0)
	{
		write(STDOUT_FILENO, "> ", 2);
		line = get_next_line(STDIN_FILENO);
		if (!line && g_signal == 0)
		{
			write(STDERR_FILENO, "\n", 1);
			ft_fprintf(STDERR_FILENO,
						"warning: here-document \
delimited by end-of-file (wanted `%s')\n",
						eof);
			break ;
		}
		if (redir_type != HEREDOC_NO_INTER)
			line = expand_line(line, ctx, HEREDOC);
		if (!line || !ft_strncmp(rm_last_char(line), eof, ft_strlen(eof) + 1))
			break ;
		ft_putendl_fd(line, hd_fd);
		free(line);
	}
	close(hd_fd);
	free(eof);
	free(line);
}

static int	wait_hd_child(t_context *ctx)
{
	int	status;

	status = 0;
	waitpid(ctx->hd_pid, &status, 0);
	if (WIFEXITED(status))
	{
		if (WEXITSTATUS(status))
		{
			if (WEXITSTATUS(status) > 128)
			{
				write(STDERR_FILENO, "\n", 1);
				g_signal = WEXITSTATUS(status) - 128;
			}
			ctx->exit_code = WEXITSTATUS(status);
			return (EXIT_FAILURE);
		}
	}
	return (EXIT_SUCCESS);
}

int	err_start_hd_child(t_context *ctx, char *eof)
{
	free(eof);
	ft_fprintf(STDERR_FILENO, "start_hd_child: %s\n", strerror(errno));
	ctx->exit_code = EXIT_FAILURE;
	return (EXIT_FAILURE);
}

/**
 * The child returns EXIT_FAILURE in every case in order to free all in parent
 * functions (it exits in read_cmds function)
 */
int	start_hd_child(t_context *ctx, t_redirect **redir, char *eof)
{
	int	hd_fd;

	if (signal(SIGINT, SIG_IGN) == SIG_ERR)
		return (err_start_hd_child(ctx, eof));
	ctx->hd_pid = fork();
	if (ctx->hd_pid == -1)
		return (err_start_hd_child(ctx, eof));
	if (!ctx->hd_pid)
	{
		if (set_hd_sigint_handler(hd_sigint_handler) == EXIT_FAILURE)
			return (err_start_hd_child(ctx, eof));
		hd_fd = open((*redir)->filename, O_WRONLY | O_CREAT | O_TRUNC, 0644);
		if (hd_fd == -1)
			return (err_start_hd_child(ctx, eof));
		write_in_file(hd_fd, eof, ctx, (*redir)->redir_type);
		return (EXIT_FAILURE);
	}
	free(eof);
	return (EXIT_SUCCESS);
}
int err_handle_heredoc(void)
{
	ft_fprintf(STDERR_FILENO, "handle_heredoc: %s\n", strerror(errno));
	return (EXIT_FAILURE);
}

int	handle_heredoc(t_context *ctx, char *str, size_t *i, t_redirect **redir)
{
	char	*eof;

	(*redir)->filename = get_hd_name();
	if (!(*redir)->filename)
		return (err_handle_heredoc());
	eof = malloc((redirlen(str) + 1) * sizeof(char));
	if (!eof)
		return (err_handle_heredoc());
	*i += extract_redirection_filename(str + *i, eof);
	if (start_hd_child(ctx, redir, eof) == EXIT_FAILURE)
		return (EXIT_FAILURE);
	if (wait_hd_child(ctx) == EXIT_FAILURE)
		return (EXIT_FAILURE);
	return (EXIT_SUCCESS);
}
