/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   redir_utils.c                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: nle-gued <nle-gued@student.42lyon.fr>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/05/13 11:26:23 by nle-gued          #+#    #+#             */
/*   Updated: 2025/05/27 11:18:53 by nle-gued         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

int	handle_output_redirection(char *str, size_t *i)
{
	int	type;

	(*i)++;
	if (str[*i] == '>')
	{
		type = OUT_TRUNC;
		(*i)++;
	}
	else
	{
		type = OUT;
	}
	return (type);
}

int	handle_input_redirection(char *str, size_t *i)
{
	int	type;

	(*i)++;
	if (str[*i] == '<')
	{
		type = HEREDOC;
		(*i)++;
	}
	else
	{
		type = IN;
	}
	return (type);
}

int	detect_redirection_type(char *str, size_t *i)
{
	int	type;

	type = -1;
	if (str[*i] == '>')
	{
		type = handle_output_redirection(str, i);
	}
	else if (str[*i] == '<')
	{
		type = handle_input_redirection(str, i);
	}
	return (type);
}

// size_t	extract_redirection_filename(char *str, char *filename)
// {
// 	size_t	i;
// 	size_t	j;
// 	char	quote;

// 	i = 0;
// 	j = 0;
// 	i = skip_spaces(str, i);
// 	while (str[i] && str[i] != ' ' && str[i] != '>' && str[i] != '<')
// 	{
// 		if (str[i] == '"' || str[i] == '\'')
// 		{
// 			quote = str[i];
// 			i++;
// 			while (str[i] == quote)
// 				i++;
// 		}
// 		else if (str[i] == quote)
// 			i++;
// 		else
// 			filename[j++] = str[i++];
// 	}
// 	filename[j] = '\0';
// 	return (i);
// }

size_t	extract_redirection_filename(char *str, char *filename)
{
	size_t	i;
	size_t	j;
	char	quote;

	i = 0;
	j = 0;
	quote = 0;
	i = skip_spaces(str, i);
	while (str[i] && (str[i] != '>' && str[i] != '<'))
	{
		if ((str[i] == '"' || str[i] == '\'') && !quote)
			quote = str[i++];
		else if (quote && str[i] == quote)
		{
			quote = 0;
			i++;
		}
		else if (!quote && (str[i] == ' '))
			break ;
		else
			filename[j++] = str[i++];
	}
	filename[j] = '\0';
	return (i);
}

char	*get_incremented_hd_name(size_t hd_i)
{
	char	*str_hd_i;
	char	*hd_name;

	str_hd_i = ft_itoa(hd_i);
	if (!str_hd_i)
	{
		printf("hd todo");
		return (NULL);
	}
	hd_name = ft_strjoin(HD_FILENAME, str_hd_i);
	if (!hd_name)
	{
		printf("hd todo");
		return (NULL);
	}
	free(str_hd_i);
	return (hd_name);
}
/**
 * @brief Generates a unique heredoc filename.
 * It is generated by appending an incrementing number to the base
 */
char	*get_hd_name(void)
{
	char	*hd_name;
	size_t	hd_i;

	hd_i = 0;
	hd_name = get_incremented_hd_name(hd_i);
	while (access(hd_name, F_OK) == 0)
	{
		free(hd_name);
		hd_name = get_incremented_hd_name(hd_i);
		hd_i++;
	}
	return (hd_name);
}

/**
 * @brief removes the last character of the string
 * @details made to remove the '\n' character at the end of the ret of gnl
 */
static char	*shorter(char *str)
{
	int	str_len;

	str_len = ft_strlen(str);
	if (str_len > 0)
		str[str_len - 1] = '\0';
	return (str);
}

int	write_in_file(int hd_fd, char *eof, t_context *ctx)
{
	char	*line;

	while (g_signal == 0)
	{
		write(STDOUT_FILENO, "> ", 2);
		line = get_next_line(STDIN_FILENO);
		if (!line)
		{
			write(STDERR_FILENO, "\n", 1);
			ft_fprintf(STDERR_FILENO,
						"warning: here-document atline 1 \
delimited by end-of-file (wanted `%s')\n",
						eof);
			break ;
		}
		line = interpretation(line, ctx);
		if (!ft_strncmp(shorter(line), eof, ft_strlen(eof) + 1))
			break ;
		write(hd_fd, line, ft_strlen(line));
		write(hd_fd, "\n", 1);
		free(line);
	}
	close(hd_fd);
	free(eof);
	free(line);
	return (0);
}

/**
 * using sigaction to allow gnl to be interrupted by a signal,
 * thanks to the sa_flags = 0
 */
void	install_sigint_handler(void (*handler)(int))
{
	struct sigaction	sa;

	sa.sa_handler = handler;
	sigemptyset(&sa.sa_mask);
	sa.sa_flags = 0;
	// todo secure signal
	sigaction(SIGINT, &sa, NULL);
}

void	sig_hd_handler(int sig)
{
	g_signal = sig;
}

int	wait_hd_child(t_context *ctx)
{
	int	status;

	status = 0;
	waitpid(ctx->hd_pid, &status, 0);
	if (WIFEXITED(status))
	{
		if (WEXITSTATUS(status))
		{
			if (WEXITSTATUS(status) > 128)
			{
				write(STDERR_FILENO, "\n", 1);
				g_signal = WEXITSTATUS(status) - 128;
			}
			ctx->exit_code = WEXITSTATUS(status);
			return (EXIT_FAILURE);
		}
	}
	return (EXIT_SUCCESS);
}

int	handle_heredoc(t_context *ctx, char *str, size_t *i, t_redirect *redir)
{
	int		hd_fd;
	char	*eof;

	redir->filename = get_hd_name();
	hd_fd = open(redir->filename, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (hd_fd == -1)
		return (EXIT_FAILURE);
	eof = malloc(redirlen(str) + 1);
	if (!eof)
	{
		close(hd_fd);
		return (EXIT_FAILURE);
	}
	*i += extract_redirection_filename(str + *i, eof);
	// todo secure signal
	signal(SIGINT, SIG_IGN);
	secure_fork(&ctx->hd_pid, ctx);
	if (!ctx->hd_pid)
	{
		install_sigint_handler(sig_hd_handler);
		write_in_file(hd_fd, eof, ctx);
		free(redir->filename);
		return (EXIT_FAILURE);
	}
	close(hd_fd);
	free(eof);
	if (wait_hd_child(ctx) == EXIT_FAILURE)
	{
		unlink(redir->filename);
		free(redir->filename);
		return (EXIT_FAILURE);
	}
	return (EXIT_SUCCESS);
}

t_redirect	*redirect_define(t_context *ctx, char *str)
{
	t_redirect	*redir;
	size_t		i;

	redir = malloc(sizeof(t_redirect));
	if (!redir)
		return (NULL);
	i = 0;
	redir->redir_type = detect_redirection_type(str, &i);
	if (redir->redir_type == HEREDOC)
	{
		if (handle_heredoc(ctx, str, &i, redir) == EXIT_FAILURE)
		{
			free(redir);
			return (NULL);
		}
	}
	else
	{
		redir->filename = malloc(redirlen(str) + 1);
		if (!redir->filename)
		{
			free(redir);
			return (NULL);
		}
		i += extract_redirection_filename(str + i, redir->filename);
	}
	redir->fd_in = -2;
	redir->fd_out = -2;
	return (redir);
}
